### ISSUE TITLE
Storyboard: intro

### ISSUE THREAD

**Issue by salvob41** [notapixelstudio/superstarfighter#124]
Prepareandstart to work on the intro storyboard

**Comment by nitaku** [comment]
1) Black screen. Then a colored vertical band appear for each of the 4 founding species, representing both their warfare and their contribution to the game. A character is depicted in the foreground with a open hand, above which an item is floating. In the background, scenes of war.
  1a) Trixens show their rockets and their expansionist attitude. Take inspiration from WWII propaganda. The item is a miniature rocket.
  1b) Robolords show their queen and their colonialist attitude. It should feel English. The item is the crown, and it hovers above the roboqueen's head rather than hand.
  1c) Mantiacs show their bombs and their aggressive attitude. Falling bombs like balls in a game. The item is a bomb.
  1d) Toriels show their force fields and their overprotective attitude. Care and prisons. The item is a force field containing a creature, and it's held between two hands.

2) Black screen. Again, 4 images appear one by one. This time, they are overlapped and with angled borders. Each image depicts an escalation in war and violence.
  2a) Trixen rockets land on a Robolord area, destroying some of them. Robolords retaliate with air-ground missiles.
  2b) Toriel's idylliac homeworld is invaded by a Robolord megastarship, while a Toriel studies a Mantiac trapped in a force field.
  2c) Mantiac starships bomb a Trixen city, destroying buildings and killing people.
  2d) Misery, dead Toriels and Toriel prisons full of innocent Trixens, Robolords and Mantiacs.

3) The "olympic" symbol of the 4 species, in gray. It is carved in stone. Four hands, one for each species,  move towards it. White light englufs the whole screen. the symbols are now colored, in a white background. The logo fades in. Wait. Fade transition to a starry background. The symbol and the logo move to the top. The game menu appears below.

**Comment by nitaku** [comment]
Abandoned in favor of a simple scene with text
